use anyhow::{Context, Result};
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct ApiSpec {
    #[allow(dead_code)]
    schema: SchemaInfo,
    #[serde(default)]
    types: Vec<TypeDef>,
    #[serde(default)]
    methods: Vec<MethodDef>,
}

#[derive(Debug, Deserialize)]
struct SchemaInfo {
    #[allow(dead_code)]
    version: String,
    #[allow(dead_code)]
    title: String,
}

#[derive(Debug, Deserialize)]
struct TypeDef {
    name: String,
    #[serde(default)]
    description: String,
    fields: Vec<FieldDef>,
}

#[derive(Debug, Deserialize)]
struct FieldDef {
    name: String,
    #[serde(rename = "type")]
    field_type: String,
}

#[derive(Debug, Deserialize)]
struct MethodDef {
    name: String,
    #[serde(default)]
    description: String,
    handler: String,
    #[serde(default)]
    params: Vec<FieldDef>,
    returns: String,
    #[serde(default)]
    streaming: bool,
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '.' || c == '_' || c == '-' {
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    result
}

fn to_camel_case(s: &str) -> String {
    let pascal = to_pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
    }
}

fn rust_type(field_type: &str) -> String {
    if field_type == "string" {
        "String".to_string()
    } else if field_type == "int" {
        "i64".to_string()
    } else if field_type == "bool" {
        "bool".to_string()
    } else if field_type == "float" {
        "f64".to_string()
    } else if field_type.starts_with("list[") && field_type.ends_with(']') {
        let inner = &field_type[5..field_type.len() - 1];
        format!("Vec<{}>", rust_type(inner))
    } else {
        field_type.to_string()
    }
}

fn dart_type(field_type: &str) -> String {
    if field_type == "string" {
        "String".to_string()
    } else if field_type == "int" {
        "int".to_string()
    } else if field_type == "bool" {
        "bool".to_string()
    } else if field_type == "float" {
        "double".to_string()
    } else if field_type.starts_with("list[") && field_type.ends_with(']') {
        let inner = &field_type[5..field_type.len() - 1];
        format!("List<{}>", dart_type(inner))
    } else {
        field_type.to_string()
    }
}

fn generate_rust_types(spec: &ApiSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by xtask codegen. DO NOT EDIT.\n");
    out.push_str("#![allow(clippy::all, unused_imports)]\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    // 1. Defined types
    for t in &spec.types {
        if !t.description.is_empty() {
            out.push_str(&format!("/// {}\n", t.description));
        }
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]\n");
        out.push_str(&format!("pub struct {} {{\n", t.name));
        for f in &t.fields {
            out.push_str(&format!("    pub {}: {},\n", f.name, rust_type(&f.field_type)));
        }
        out.push_str("}\n\n");
    }

    // 2. Method parameter types
    for m in &spec.methods {
        let param_struct = format!("{}Params", to_pascal_case(&m.name));
        out.push_str(&format!("/// Request parameters for `{}`\n", m.name));
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]\n");
        out.push_str(&format!("pub struct {} {{\n", param_struct));
        for p in &m.params {
            out.push_str(&format!("    pub {}: {},\n", p.name, rust_type(&p.field_type)));
        }
        out.push_str("}\n\n");
    }

    out
}

fn generate_rust_dispatch(spec: &ApiSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by xtask codegen. DO NOT EDIT.\n");
    out.push_str("#![allow(clippy::all, unused_imports)]\n\n");
    out.push_str("use code_lite_rpc::protocol::{error_codes, JsonRpcRequest, JsonRpcResponse};\n");
    out.push_str("use crate::CodeLiteContext;\n");
    out.push_str("use super::types::*;\n\n");

    out.push_str("/// Dispatches an incoming JSON-RPC request to the appropriate handler.\n");
    out.push_str("pub fn dispatch_rpc(ctx: *mut CodeLiteContext, req: &JsonRpcRequest) -> JsonRpcResponse {\n");
    out.push_str("    match req.method.as_str() {\n");

    for m in &spec.methods {
        let param_struct = format!("{}Params", to_pascal_case(&m.name));
        out.push_str(&format!("        {:?} => {{\n", m.name));
        if m.params.is_empty() {
            out.push_str(&format!(
                "            match {}(ctx, {}::default()) {{\n",
                m.handler, param_struct
            ));
        } else {
            out.push_str(&format!(
                "            let params: {} = match req.params.as_ref() {{\n",
                param_struct
            ));
            out.push_str("                Some(val) => match serde_json::from_value(val.clone()) {\n");
            out.push_str("                    Ok(p) => p,\n");
            out.push_str("                    Err(e) => return JsonRpcResponse::err(req.id, error_codes::INVALID_PARAMS, e.to_string()),\n");
            out.push_str("                },\n");
            out.push_str("                None => return JsonRpcResponse::err(req.id, error_codes::INVALID_PARAMS, \"Missing required params\"),\n");
            out.push_str("            };\n");
            out.push_str(&format!("            match {}(ctx, params) {{\n", m.handler));
        }
        out.push_str("                Ok(res) => JsonRpcResponse::success(req.id, serde_json::to_value(res).unwrap()),\n");
        out.push_str("                Err(err) => JsonRpcResponse::err(req.id, error_codes::SERVER_ERROR, err),\n");
        out.push_str("            }\n");
        out.push_str("        }\n");
    }

    out.push_str("        _ => JsonRpcResponse::err(\n");
    out.push_str("            req.id,\n");
    out.push_str("            error_codes::METHOD_NOT_FOUND,\n");
    out.push_str("            format!(\"Method not found: {}\", req.method),\n");
    out.push_str("        ),\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn generate_dart_client(spec: &ApiSpec) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by xtask codegen. DO NOT EDIT DIRECTLY.\n");
    out.push_str("// Generated from core_api.toml.\n\n");
    out.push_str("import 'dart:async';\n");
    out.push_str("import 'dart:convert';\n");
    out.push_str("import 'dart:ffi';\n");
    out.push_str("import '../../ffi/codelite_bindings.dart';\n\n");

    // JsonRpcException
    out.push_str("class JsonRpcException implements Exception {\n");
    out.push_str("  final int code;\n");
    out.push_str("  final String message;\n");
    out.push_str("  final dynamic data;\n\n");
    out.push_str("  const JsonRpcException(this.code, this.message, [this.data]);\n\n");
    out.push_str("  @override\n");
    out.push_str("  String toString() => 'JsonRpcException($code): $message';\n");
    out.push_str("}\n\n");

    // JsonRpcTransport interface
    out.push_str("abstract class JsonRpcTransport {\n");
    out.push_str("  Future<dynamic> sendRequest(String method, Map<String, dynamic> params);\n");
    out.push_str("}\n\n");

    // FfiJsonRpcTransport
    out.push_str("class FfiJsonRpcTransport implements JsonRpcTransport {\n");
    out.push_str("  final CodeLiteBindings bindings;\n");
    out.push_str("  final Pointer<Void> ctxPtr;\n");
    out.push_str("  int _nextId = 1;\n\n");
    out.push_str("  FfiJsonRpcTransport({required this.bindings, required this.ctxPtr});\n\n");
    out.push_str("  @override\n");
    out.push_str("  Future<dynamic> sendRequest(String method, Map<String, dynamic> params) async {\n");
    out.push_str("    final id = _nextId++;\n");
    out.push_str("    final req = jsonEncode({\n");
    out.push_str("      'jsonrpc': '2.0',\n");
    out.push_str("      'id': id,\n");
    out.push_str("      'method': method,\n");
    out.push_str("      'params': params,\n");
    out.push_str("    });\n");
    out.push_str("    final resStr = bindings.jsonRpcCall(ctxPtr, req);\n");
    out.push_str("    if (resStr == null || resStr.isEmpty) {\n");
    out.push_str("      throw const JsonRpcException(-32603, 'Null or empty response from native JSON-RPC call');\n");
    out.push_str("    }\n");
    out.push_str("    final decoded = jsonDecode(resStr) as Map<String, dynamic>;\n");
    out.push_str("    if (decoded.containsKey('error') && decoded['error'] != null) {\n");
    out.push_str("      final err = decoded['error'] as Map<String, dynamic>;\n");
    out.push_str("      throw JsonRpcException(err['code'] as int? ?? -32000, err['message'] as String? ?? 'Unknown error', err['data']);\n");
    out.push_str("    }\n");
    out.push_str("    return decoded['result'];\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    // Data models
    for t in &spec.types {
        if !t.description.is_empty() {
            out.push_str(&format!("/// {}\n", t.description));
        }
        out.push_str(&format!("class {} {{\n", t.name));
        for f in &t.fields {
            let dart_f_type = dart_type(&f.field_type);
            let camel = to_camel_case(&f.name);
            out.push_str(&format!("  final {} {};\n", dart_f_type, camel));
        }
        out.push_str("\n");

        // Constructor
        out.push_str(&format!("  const {}({{\n", t.name));
        for f in &t.fields {
            out.push_str(&format!("    required this.{},\n", to_camel_case(&f.name)));
        }
        out.push_str("  });\n\n");

        // fromJson
        out.push_str(&format!("  factory {}.fromJson(Map<String, dynamic> json) {{\n", t.name));
        out.push_str(&format!("    return {}(\n", t.name));
        for f in &t.fields {
            let camel = to_camel_case(&f.name);
            let raw_name = &f.name;
            if f.field_type == "string" {
                out.push_str(&format!("      {}: json['{}'] as String? ?? '',\n", camel, raw_name));
            } else if f.field_type == "int" {
                out.push_str(&format!("      {}: json['{}'] as int? ?? 0,\n", camel, raw_name));
            } else if f.field_type == "bool" {
                out.push_str(&format!("      {}: json['{}'] as bool? ?? false,\n", camel, raw_name));
            } else if f.field_type == "float" {
                out.push_str(&format!("      {}: (json['{}'] as num?)?.toDouble() ?? 0.0,\n", camel, raw_name));
            } else if f.field_type.starts_with("list[") && f.field_type.ends_with(']') {
                let inner = &f.field_type[5..f.field_type.len() - 1];
                if inner == "string" || inner == "int" || inner == "bool" {
                    out.push_str(&format!("      {}: (json['{}'] as List<dynamic>?)?.map((e) => e as {}).toList() ?? [],\n", camel, raw_name, dart_type(inner)));
                } else {
                    out.push_str(&format!("      {}: (json['{}'] as List<dynamic>?)?.map((e) => {}.fromJson(e as Map<String, dynamic>)).toList() ?? [],\n", camel, raw_name, inner));
                }
            } else {
                out.push_str(&format!("      {}: {}.fromJson(json['{}'] as Map<String, dynamic>? ?? {{}}),\n", camel, f.field_type, raw_name));
            }
        }
        out.push_str("    );\n");
        out.push_str("  }\n\n");

        // toJson
        out.push_str("  Map<String, dynamic> toJson() => {\n");
        for f in &t.fields {
            let camel = to_camel_case(&f.name);
            let raw_name = &f.name;
            if f.field_type.starts_with("list[") && f.field_type.ends_with(']') {
                let inner = &f.field_type[5..f.field_type.len() - 1];
                if inner == "string" || inner == "int" || inner == "bool" {
                    out.push_str(&format!("    '{}': {},\n", raw_name, camel));
                } else {
                    out.push_str(&format!("    '{}': {}.map((e) => e.toJson()).toList(),\n", raw_name, camel));
                }
            } else if f.field_type != "string" && f.field_type != "int" && f.field_type != "bool" && f.field_type != "float" {
                out.push_str(&format!("    '{}': {}.toJson(),\n", raw_name, camel));
            } else {
                out.push_str(&format!("    '{}': {},\n", raw_name, camel));
            }
        }
        out.push_str("  };\n");
        out.push_str("}\n\n");
    }

    // CoreApiClient class
    out.push_str("/// Strongly typed CoreApiClient generated from core_api.toml IDL contract.\n");
    out.push_str("class CoreApiClient {\n");
    out.push_str("  final JsonRpcTransport transport;\n\n");
    out.push_str("  CoreApiClient({required this.transport});\n\n");
    out.push_str("  factory CoreApiClient.fromBindings({\n");
    out.push_str("    required CodeLiteBindings bindings,\n");
    out.push_str("    required Pointer<Void> ctxPtr,\n");
    out.push_str("  }) {\n");
    out.push_str("    return CoreApiClient(transport: FfiJsonRpcTransport(bindings: bindings, ctxPtr: ctxPtr));\n");
    out.push_str("  }\n\n");

    for m in &spec.methods {
        let method_name = to_camel_case(&m.name);
        if !m.description.is_empty() {
            out.push_str(&format!("  /// {}\n", m.description));
        }

        if m.streaming {
            out.push_str(&format!(
                "  Stream<{}> {}({{\n",
                m.returns, method_name
            ));
            for p in &m.params {
                let d_type = dart_type(&p.field_type);
                let camel = to_camel_case(&p.name);
                if p.field_type == "bool" && p.name == "stream" {
                    out.push_str(&format!("    {} {} = true,\n", d_type, camel));
                } else {
                    out.push_str(&format!("    required {} {},\n", d_type, camel));
                }
            }
            out.push_str("  }) async* {\n");
            out.push_str("    final params = <String, dynamic>{\n");
            for p in &m.params {
                let camel = to_camel_case(&p.name);
                out.push_str(&format!("      '{}': {},\n", p.name, camel));
            }
            out.push_str("    };\n");
            out.push_str(&format!(
                "    final res = await transport.sendRequest({:?}, params);\n",
                m.name
            ));
            out.push_str(&format!(
                "    yield {}.fromJson(res as Map<String, dynamic>);\n",
                m.returns
            ));
            out.push_str("  }\n\n");
        } else {
            out.push_str(&format!(
                "  Future<{}> {}({{\n",
                m.returns, method_name
            ));
            for p in &m.params {
                let d_type = dart_type(&p.field_type);
                let camel = to_camel_case(&p.name);
                out.push_str(&format!("    required {} {},\n", d_type, camel));
            }
            out.push_str("  }) async {\n");
            out.push_str("    final params = <String, dynamic>{\n");
            for p in &m.params {
                let camel = to_camel_case(&p.name);
                if p.field_type.starts_with("list[") {
                    let inner = &p.field_type[5..p.field_type.len() - 1];
                    if inner == "string" || inner == "int" || inner == "bool" {
                        out.push_str(&format!("      '{}': {},\n", p.name, camel));
                    } else {
                        out.push_str(&format!("      '{}': {}.map((e) => e.toJson()).toList(),\n", p.name, camel));
                    }
                } else if p.field_type != "string" && p.field_type != "int" && p.field_type != "bool" && p.field_type != "float" {
                    out.push_str(&format!("      '{}': {}.toJson(),\n", p.name, camel));
                } else {
                    out.push_str(&format!("      '{}': {},\n", p.name, camel));
                }
            }
            out.push_str("    };\n");
            out.push_str(&format!(
                "    final res = await transport.sendRequest({:?}, params);\n",
                m.name
            ));
            out.push_str(&format!(
                "    return {}.fromJson(res as Map<String, dynamic>);\n",
                m.returns
            ));
            out.push_str("  }\n\n");
        }
    }

    out.push_str("}\n");

    out
}

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    let cmd = args.get(1).map(|s| s.as_str()).unwrap_or("codegen");

    if cmd != "codegen" {
        eprintln!("Usage: cargo run -p xtask -- codegen");
        std::process::exit(1);
    }

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .context("Missing crates dir")?
        .parent()
        .context("Missing workspace root")?;

    let toml_path = workspace_root.join("core_api.toml");
    println!("Reading IDL spec from {}", toml_path.display());
    let toml_content = fs::read_to_string(&toml_path)
        .with_context(|| format!("Failed to read {}", toml_path.display()))?;

    let spec: ApiSpec = toml::from_str(&toml_content)
        .with_context(|| "Failed to parse core_api.toml")?;

    println!(
        "Parsed IDL: {} types, {} methods",
        spec.types.len(),
        spec.methods.len()
    );

    // 1. Rust Output
    let rust_gen_dir = workspace_root.join("crates/code-lite-ffi/src/generated");
    fs::create_dir_all(&rust_gen_dir)?;

    let rust_types_content = generate_rust_types(&spec);
    let rust_types_path = rust_gen_dir.join("types.rs");
    fs::write(&rust_types_path, rust_types_content)?;
    println!("Generated Rust types -> {}", rust_types_path.display());

    let rust_dispatch_content = generate_rust_dispatch(&spec);
    let rust_dispatch_path = rust_gen_dir.join("dispatch.rs");
    fs::write(&rust_dispatch_path, rust_dispatch_content)?;
    println!("Generated Rust dispatch -> {}", rust_dispatch_path.display());

    let rust_mod_path = rust_gen_dir.join("mod.rs");
    let rust_mod_content = "// Auto-generated by xtask codegen. DO NOT EDIT.\npub mod types;\npub mod dispatch;\npub use types::*;\npub use dispatch::*;\n";
    fs::write(&rust_mod_path, rust_mod_content)?;
    println!("Generated Rust mod -> {}", rust_mod_path.display());

    // 2. Dart Output
    let dart_gen_dir = workspace_root.join("apps/code_lite_ui/lib/core/api/generated");
    fs::create_dir_all(&dart_gen_dir)?;

    let dart_client_content = generate_dart_client(&spec);
    let dart_client_path = dart_gen_dir.join("core_api_client.dart");
    fs::write(&dart_client_path, dart_client_content)?;
    println!("Generated Dart client -> {}", dart_client_path.display());

    println!("xtask codegen completed successfully!");
    Ok(())
}
